using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace RoboNet.EMVParser.SourceGenerators;

[Generator]
public class WellKnownTagsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext initContext)
    {
        IncrementalValuesProvider<AdditionalText> textFiles =
            initContext.AdditionalTextsProvider.Where(static file => file.Path.EndsWith("well-known-tags.txt"));

        IncrementalValuesProvider<(string name, string content)> namesAndContents =
            textFiles.Select((text, cancellationToken) => (name: Path.GetFileNameWithoutExtension(text.Path),
                content: text.GetText(cancellationToken)!.ToString()));

        initContext.RegisterSourceOutput(namesAndContents, (spc, nameAndContent) =>
        {
            StringBuilder builder = new StringBuilder();

            StringBuilder tagNamesBuilder = new StringBuilder();

            var lines = nameAndContent.content.Split('\n');
            foreach (var line in lines)
            {
                if (string.IsNullOrWhiteSpace(line))
                    continue;

                var parts = line.Split(';');

                if (parts.Length != 3)
                    continue;

                tagNamesBuilder.AppendLine($"{{\"{parts[0].Trim('"').Trim()}\",\"{parts[1].Trim('"').Trim()}\"}},");

                builder.AppendLine($"        /// <summary>");
                builder.AppendLine($"        /// {parts[2].Trim('"').Trim()}");
                builder.AppendLine($"        /// </summary>");

                var tagName = parts[1].Trim('"').Trim().Replace(" ", "").Replace(",", "").Replace("-", "")
                    .Replace("–", "").Replace("(", "").Replace(")", "");

                builder.AppendLine(
                    $"        public readonly static string {tagName} = \"{parts[0].Trim('"').Trim()}\";");
            }

            spc.AddSource($"EMVTags.g", SourceText.From($@"
    // <auto-generated/>

#nullable enable
    using System.Collections.Generic;
    public partial class EMVTags
    {{
        private static Dictionary<string, string> tags = new Dictionary<string, string>()
        {{
            {tagNamesBuilder}
        }};

        public static string? GetTagName(string tag)
        {{
            if (tags.TryGetValue(tag, out var description))
            {{
                return description;
            }}
            return null;
        }}

{builder}
    }}
#nullable disable", Encoding.UTF8));
        });
    }
}